name: Update IP List

on:
  schedule:
    - cron: '0 */3 * * *' # 每3小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

permissions:
  contents: write  # 关键：允许 GITHUB_TOKEN 拥有写权限

jobs:
  update-ip-list:
    runs-on: ubuntu-latest

    steps:
      # 使用 GITHUB_TOKEN 拉取代码，确保有写权限
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 
          # 1. 安装 playwright 模块
          # pip install playwright
          
          # 2. 安装浏览器（必须！否则会报错）
          # playwright install chromium
          
          # 3. （可选）安装系统依赖（Linux 推荐）
          # playwright install-deps
          
      # 执行
      - name: Run scripts
        run: |
          python ${{ github.workspace }}/collect_ips.py
         #  python ${{ github.workspace }}/get_cf_sg.py
          python ${{ github.workspace }}/youxuan.py

          
      - name: Commit and push changes
        run: |
          git config --global user.email "tianshideyou@proton.me"
          git config --global user.name "tianshipapa"
          if [ -n "$(git status --porcelain)" ]; then
            git add ip.txt SG.txt US.txt HK.txt JP.txt
            git commit -m "Automatic update"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
